- 
  name: xbs_play_1
  hosts: all
  tasks:
      - name: Execute single command "date"
        command: date

      - name: Execute multiply commands in the shell
        shell: |
                echo "done remotely:" > /tmp/dt
                date >> /tmp/dt
                pwd >> /tmp/dt

      - name: Installing httpd (testing sudo)
        shell: |
                sudo yum install httpd -y
